version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/docker/dev"
    target-branch: "dev"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/docker/release"
    target-branch: "release"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "daily"
    labels:
      - automerge
