# Only app compose file

networks:
  weather-app-network:
    driver: bridge

services:
  weather-app:
    image: ghcr.io/crut0i/weatherapp
    container_name: weather-app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    volumes:
      - ${APP_ENV_PATH}:/app/config/.env:ro
      - ${HYPERCORN_CONF_PATH}:/app/config/hypercorn.toml
    networks:
      - weather-app-network
      