name: Command Dispatch

on:
  issue_comment:
    types: [created]

jobs:
  CommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Command Dispatch
        uses: peter-evans/slash-command-dispatch@v4.0.0
        with:
          token: ${{ secrets.PAT }}
          reactions: true
          permission: write
          issue-type: pull-request
          commands: format
