name: Delete branch

on:
  pull_request:
    types: ["closed"]
    branches: ["dev"]

permissions:
  contents: write

jobs:
  delete-branch:
    if: ${{ github.event.pull_request.merged == true && github.actor != 'dependabot[bot]' &&github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Delete head branch
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branchName = context.payload.pull_request.head.ref;
            await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `heads/${branchName}`,
            });
