name: Dependabot PRs

on:
  pull_request:
    types: [opened, edited, reopened, labeled, unlabeled, synchronize]
  pull_request_review:
    types: [submitted]
  check_suite:
    types: [completed]
  status:

jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Merge Dependabot PR
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          COMMIT_TITLE: "[chore] Merge Dependabot PR"
          COMMIT_MESSAGE: "🤖 Automatically merged Dependabot update"
