name: Docker Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "LICENSE"
      - "**.md"
      - "tests/**"
    tags:
      - "v*.*.*"
  workflow_dispatch:
  workflow_call:

jobs:
  docker-build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'github-actions[bot]' && !contains(github.event.head_commit.message, '[[skip docker build]]') }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Metadata
        id: meta
        run: |
          repo=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          echo "TAG=ghcr.io/${repo}" >> $GITHUB_OUTPUT

      - name: Build and push release image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/release/Dockerfile
          push: true
          tags: |
            ${{ steps.meta.outputs.TAG }}:latest
            ${{ steps.meta.outputs.TAG }}:${{ github.sha }}
